version: '2'
services:
  hub:
    image: sethuster/selenium-hub
    ports:
      - "4444"
  firefox:
    image: sethuster/node-firefox-debugx
    ports:
      - "5900"
    depends_on:
      - hub
  mustadio:
    image: yetanotherlucas/mustadio
    ports:
      - "3000"
  gridium:
    build: .
    command: "tail -f /dev/null"
